version: "2.1"

services:
  req:
    build:
      context: .
      dockerfile: deploy/Dockerfile-requirements
    image: social-network-req

  base:
    build:
      context: .
      dockerfile: deploy/Dockerfile-base
    image: social-network-base

  server:
    image: social-network-base
    ports:
      - "8000:8000"
    env_file:
      - "./social_network/local_settings.py"
    volumes:
      - "./static:/app/static"
      - "./media:/app/media"
    restart: unless-stopped
    command: uwsgi --ini ./deploy/uwsgi.ini

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
      MYSQL_USER: social_network_user
      MYSQL_PASSWORD: social_network_pass
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - "./deploy/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./static:/static"
      - "./media:/media"
